<!DOCTYPE html>

<head>
    <title>Document</title>
</head>

<body>
    <script>
        //try-catch
        //try문에서 예외가 발생할 경우 catch로 빠져서 그안의 실행문을 실행.
        //예외 발생시 try-catch-finallly //예외없으면 try-finally

        try {
            consoel.log("콘솔에 출력")
        } catch (error) {
            console.log(error.name);
            console.log(error.message)
        }


        var x = 2;
        var y = 3;

        // console.log(x + y);


        try {
            if (x == 0) {
                throw "value is zero.";
            } //throw만나면 무조건 catch로 감
        } catch (error) {
            console.log(error);
        } finally {
            //finally는 에러나든 안나든 무조건 실행됨.
            console.log("try/catch를 모두 실행한 후 반드시 실행하는 부분")
        }
    </script>
</body>

</html>